// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhznsgiiablujtxrxawj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoem5zZ2lpYWJsdWp0eHJ4YXdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NjcyMTEsImV4cCI6MjA2MDA0MzIxMX0.EV3PFa9_vTyNIOTPfW3NvedDdNXGo2m4It1ll059wqM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);